In [17]:

import numpy as np 

# Training set
X_train=np.array(([300,99,6.8],[308,103,8.36],[329,110,9.15],[332,118,9.36]), dtype=float)
y_train=np.array(([0.36],[0.7],[0.84],[0.9]), dtype=float)

# Testing set
X_test=np.array(([296,95,7.54],[293,97,7.8],[325,112,8.96]), dtype=float)
y_test=np.array(([0.44],[0.64],[0.8]), dtype=float)
 



# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(3,3) # considering we have 3 nodes in the hidden layer 
        self.weights2 = np.random.rand(3,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()
        

NN = NeuralNetwork(X_train,y_train)
for i in range(5): # trains the NN 1,000 times
    print ("for iteration # " + str(i) + "\n")
    print ("Actual Output: \n" + str(y_train))
    print ("Predicted Output: \n" + str(NN.feedforward()))
    print ("Loss: \n" + str(np.mean(np.square(y_train - NN.feedforward())))) # mean sum squared loss
    print ("\n")
  
    NN.train(X_train, y_train)

for iteration # 0

Actual Output: 
[[0.36]
 [0.7 ]
 [0.84]
 [0.9 ]]
Predicted Output: 
[[0.89116911]
 [0.89116911]
 [0.89116911]
 [0.89116911]]
Loss: 
0.08034563045779815


for iteration # 1

Actual Output: 
[[0.36]
 [0.7 ]
 [0.84]
 [0.9 ]]
Predicted Output: 
[[0.83993685]
 [0.83993685]
 [0.83993685]
 [0.83993685]]
Loss: 
0.06338232106420723


for iteration # 2

Actual Output: 
[[0.36]
 [0.7 ]
 [0.84]
 [0.9 ]]
Predicted Output: 
[[0.76963188]
 [0.76963188]
 [0.76963188]
 [0.76963188]]
Loss: 
0.04864859828560659


for iteration # 3

Actual Output: 
[[0.36]
 [0.7 ]
 [0.84]
 [0.9 ]]
Predicted Output: 
[[0.71298757]
 [0.71298757]
 [0.71298757]
 [0.71298757]]
Loss: 
0.0439686768891573


for iteration # 4

Actual Output: 
[[0.36]
 [0.7 ]
 [0.84]
 [0.9 ]]
Predicted Output: 
[[0.69975952]
 [0.69975952]
 [0.69975952]
 [0.69975952]]
Loss: 
0.04380005783012142




In [20]:

import numpy as np 

# Training set
X_train=np.array(([300,99,6.8],[308,103,8.36],[329,110,9.15],[332,118,9.36]), dtype=float)
y_train=np.array(([0.36],[0.7],[0.84],[0.9]), dtype=float)

# Testing set
X_test=np.array(([296,95,7.54],[293,97,7.8],[325,112,8.96]), dtype=float)
y_test=np.array(([0.44],[0.64],[0.8]), dtype=float)

# 1. Build a two-layers neural network of one input layer (three nodes)
#   one hidden layer (three nodes with sigmoid activation function) 
#   and one output layer(one node with no activation function).

layer1=np.ndarray(shape=(3,3), dtype=float)
layer2=np.ndarray(shape=(3,1), dtype=float)
layer3=np. zeros(y_train.shape)

def sigmoid(X):
    return 1/(1+np.exp(-X))

def sigmoid_derivative(X):
    return X * (1 - X)

#2. Initialize the parameters with some random values.
w1 = np.random.rand(3,3)
w2 = np.random.rand(3,1)

#3. Perform a feed-forward stage to propagate the input forward through the network.
def feedforward(X):
    global w2
    global w1
    global layer1
    global layer2
    layer1 = sigmoid(np.dot(X,w1))
    layer2 = sigmoid(np.dot(layer1,w2))
    return layer2


#4. Preform the back-propagation algorithm using sum square error (SSE).
def backprop(X,y,output):
    global w2
    global w1
    global layer1
    global layer2
    d_w2 = np.dot(layer1.T, 2*(y -output)*sigmoid_derivative(layer2))
    d_w1 = np.dot(X.T, np.dot(2*(y-output)*sigmoid_derivative(output), w2.T)*sigmoid_derivative(layer1))
    w2+=d_w2
    w1+=d_w1

for i in range(5):
    output=feedforward(X_train)
    backprop(X_train,y_train,output)
    print ("for iteration # ",i,"\n")
    
    #5. Print the content of the input/output of hidden layers and output layer at the feedforward stages.
    print ("input/output of hidden layers: \n",X_train,'\n', layer1,'\n')
    print ("input/output of output layer: \n",layer1,'\n', layer2,'\n')
    
    #6. Print the content of the weight matrices after each epoch (4 epochs).
    print ("the weight matrices: \n",w1,'\n',w2)
    print ("\n")
#7. Test and report the result of classifying the testing examples.

print ("------------------------------------------\n#For testing #\n")
output=feedforward(X_test)
print ("Actual Output: \n" + str(y_test))
print ("Predicted Output: \n" + str(output))
print ("Mean sum squared: \n" + str(np.mean(np.square(y_test - output)))) # mean sum squared

for iteration #  0 

input/output of hidden layers: 
 [[300.    99.     6.8 ]
 [308.   103.     8.36]
 [329.   110.     9.15]
 [332.   118.     9.36]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

input/output of output layer: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 [[0.82497461]
 [0.82497461]
 [0.82497461]
 [0.82497461]] 

the weight matrices: 
 [[0.81173703 0.9407596  0.934431  ]
 [0.96867931 0.27855372 0.14002839]
 [0.1252226  0.33769497 0.60738648]] 
 [[ 0.49013839]
 [-0.05105786]
 [ 0.67825452]]


for iteration #  1 

input/output of hidden layers: 
 [[300.    99.     6.8 ]
 [308.   103.     8.36]
 [329.   110.     9.15]
 [332.   118.     9.36]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

input/output of output layer: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 [[0.75349406]
 [0.75349406]
 [0.75349406]
 [0.75349406]] 

the weight matrices: 
 [[0.81173703 0.9407596  0.934431  ]
 [0.96867931 0.27855372 0.14002839]
 [0.1252226  0.33769497 0.60738